# Generated by Django 4.2.7 on 2024-01-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='sulg',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
