# Generated by Django 4.2.7 on 2024-01-23 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_servicemodel_sulg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicemodel',
            old_name='sulg',
            new_name='slug',
        ),
    ]
